#ifndef ROBOT_COMMANDER_H
#define ROBOT_COMMANDER_H

#include <mutex>
#include <Eigen/Dense>
#include <std_msgs/Float64.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/WrenchStamped.h>
#include <sensor_msgs/JointState.h>
#include "ros/ros.h"

// Action Client
#include <actionlib/client/simple_action_client.h>
#include <actionlib/client/terminal_state.h>
#include <control_msgs/FollowJointTrajectoryAction.h>

// Service Includes
#include "adaptive_grasping/velCommand.h"
#include <std_srvs/SetBool.h>

// Filter Includes
#include "filters/filter_chain.h"

/**
* @brief This class is called by the adaptive_grasping method to close the
* hand and move the arm robot in order to execute the references generated by the
* contactPreserver according to the adaptive_grasping algorithm.
* @uses velocity controller for the hand (if softhand)
* @uses cartesian velocity controller for the panda arm (palm)
*
*/

namespace adaptive_grasping {

  class robotCommander {

  public:

    /** CONSTRUCTOR
    * @brief Default constructor for robotCommander
    *
    * @param hand_topic_
    *   the topic for commanding the hand
    * @param arm_topic_
    *   the topic for commanding the arm
    * @return null
    */
    robotCommander(std::string hand_topic_, std::string arm_topic_);

    /** DESTRUCTOR
    * @brief Default destructor for robotCommander
    *
    * @param null
    * @return null
    */
    ~robotCommander();

  private:

    // Basic variables
    ros::NodeHandle nh_rc;
    ros::ServiceServer rc_server;       // For getting velocity requests and commanding the robot
    ros::ServiceServer emerg_server;    // For stopping the robot in case of emergency

    // A bool for emergency stop (used for setReferences in performRobotCommand)
    bool emergency;

    // A mutual exclusion lock for the variables of this class
    std::mutex robot_commander_mutex;

    // A sensor message and an Eigen vector containing the latest available joints of the hand
    sensor_msgs::JointState::ConstPtr full_joint_state;
    Eigen::VectorXd current_joints_vector;

    // The topic names for hand commanding and arm commanding
    std::string hand_topic;
    std::string arm_topic;

    // The commanded values given by contactPreserver (where service msg is saved)
    Eigen::VectorXd x_ref;
    Eigen::VectorXd filtered_x_ref;

    // The commanded values given by contactPreserver (divided)
    Eigen::VectorXd hand_ref;
    geometry_msgs::Twist palm_ref;

    // A sensor message containing the latest available joints of the hand
    sensor_msgs::JointState current_joints;

    // Publishers to hand and arm controllers
    ros::Publisher pub_hand;
    ros::Publisher pub_arm;
    ros::Publisher pub_sigma_debug;
    ros::Publisher pub_twist_debug;

    // Command vars: messages to be published
    geometry_msgs::Twist cmd_twist;
    std_msgs::Float64 cmd_syn;
    geometry_msgs::WrenchStamped twist_wrench;          // Publishing twist as a wrench (For Debugging)
    double vel_limit = 0.05;                            // Upper limit for all joint velocities

    // A vector of filters for eventually filtering the references to be sent to the controllers (TODO: use vector of filters)
    // std::vector<filters::FilterChain<double>> ref_filter;

    // A series of double filter chains for reference low pass filtering
    bool enable_filter = true;
    filters::FilterChain<double> ref_1_filter;
    filters::FilterChain<double> ref_2_filter;
    filters::FilterChain<double> ref_3_filter;
    filters::FilterChain<double> ref_4_filter;
    filters::FilterChain<double> ref_5_filter;
    filters::FilterChain<double> ref_6_filter;
    filters::FilterChain<double> ref_7_filter;

    /** PERFORMROBOTCOMMAND
    * @brief Private callback function of the main service of robotCommander
    *
    * @param req
    * @param res
    * @return null
    */
    bool performRobotCommand(adaptive_grasping::velCommand::Request &req,
        adaptive_grasping::velCommand::Response &res);

    /** ENFORCELIMITS
    * @brief Private function to check joint velocity limits and to follow them
    *
    * @param vel_ref_
    *   the vector containing the reference twist for the palm (must be 6d and passed by reference)
    * @return ok_limits
    */
    bool enforceLimits(Eigen::VectorXd& vel_ref_);

    /** SETREFERENCES
    * @brief Private function to set the twist references of palm and the speed of hand joints
    *
    * @param hand_ref_
    *   the vector containing the hand joints' speeds
    * @param palm_ref_ (must be 6d)
    *   the vector containing the reference twist for the palm
    * @return null
    */
    void setReferences(Eigen::VectorXd hand_ref_, Eigen::VectorXd palm_ref_);

    /** EMERGENCYSTOP
    * @brief A callback for stopping the motion of robot in case of emergency
    *
    * @param req/res
    * @return null
    */
    bool emergencyStop(std_srvs::SetBool::Request &req, std_srvs::SetBool::Response &res);

  };

}


#endif // ROBOT_COMMANDER_H
