#ifndef ROBOT_COMMANDER_H
#define ROBOT_COMMANDER_H

#include <mutex>
#include <Eigen/Dense>
#include <geometry_msgs/Twist.h>
#include <sensor_msgs/JointState.h>
#include "ros/ros.h"

// Action Client
#include <actionlib/client/simple_action_client.h>
#include <actionlib/client/terminal_state.h>
#include <control_msgs/FollowJointTrajectoryAction.h>


/**
* @brief This class is called by the adaptive_grasping method to close the
* hand and move the kuka in order to execute the references generated by the
* contactPreserver according to the adaptive_grasping algorithm.
* @uses joint trajectory controller for the hand
* @uses twist controller for the kuka arm (palm)
*
*/

namespace adaptive_grasping {

  class robotCommander {

  public:

    /** CONSTRUCTOR
    * @brief Default constructor for robotCommander
    *
    * @param hand_topic_
    *   the topic for commanding the hand closure
    * @param arm_topic_
    *   the topic for commanding the arm
    * @return null
    */
    robotCommander(std::string hand_topic_, std::string arm_topic_,
      std::vector<std::string> joint_names_vec_);

    /** DESTRUCTOR
    * @brief Default destructor for robotCommander
    *
    * @param null
    * @return null
    */
    ~robotCommander();

    /** SETREFERENCES
    * @brief Public function to set the references of palm and hand joints
    *
    * @param joints_ref_
    *   the vector containing the hand joints' speeds
    * @param palm_ref_ (must be 6d)
    *   the vector containing the reference twist for the palm
    * @return null
    */
    void setReferences(Eigen::VectorXd joints_ref_, Eigen::VectorXd palm_ref_);

    /** MOVEHANDARM
    * @brief Public function to move the hand and/or arm (if twist = 0, no arm)
    * Executes the references previously set by setReferences function
    *
    * @param null
    * @return null
    */
    void sendRefToArm();

  private:

    // Basic variables
    ros::NodeHandle nh_rc;
    ros::Subscriber joint_state_sub;          // For getting hand joint states

    // A mutual exclusion lock for the variables of this class
    std::mutex robot_commander_mutex;

    // A data structure containing the names of the hand joints in order
    std::vector<std::string> joint_names_vec;

    // The topic names for hand commanding and arm commanding
    std::string hand_topic;
    std::string arm_topic;

    // The commanded values given by contactPreserver (divided)
    Eigen::VectorXd joints_ref;
    geometry_msgs::Twist palm_ref;

    // A sensor message containing the latest available joints of the hand
    sensor_msgs::JointState current_joints;

    // An action client for the hand and a publisher for the arm
    std::shared_ptr<actionlib::SimpleActionClient<control_msgs::FollowJointTrajectoryAction>> act_hand;
    ros::Publisher pub_arm;

    /** GETJOINTSTATES
    * @brief Private callback function to get and write joint states of the hand
    *
    * @param null
    * @return null
    */
    void getJointStates(const sensor_msgs::JointStateConstPtr& msg);

    /** SENDREFTOHAND
    * @brief Private function to close the hand with a given reference speed
    * The vector joints_ref set by setReferences will be executed
    *
    * @param null
    * @return null
    */
    void sendRefToHand();

    /** SENDREFTOARM
    * @brief Private function to move the palm of the arm, following a twist
    *
    * @param palm_ref_
    *   the twist vector containing the reference motion of the palm
    * @return null
    */
    void sendRefToArm(geometry_msgs::Twist palm_ref_);

  };

}


#endif // ROBOT_COMMANDER_H
