#ifndef ROBOT_COMMANDER_H
#define ROBOT_COMMANDER_H

#include <Eigen/Dense>
#include <geometry_msgs/Twist.h>
#include "ros/ros.h"

// Action Client
#include <actionlib/client/simple_action_client.h>
#include <actionlib/client/terminal_state.h>
#include <control_msgs/FollowJointTrajectoryAction.h>


/**
* @brief This class is called by the adaptive_grasping method to close the
* hand and move the kuka in order to execute the references generated by the
* contactPreserver according to the adaptive_grasping algorithm.
* @uses joint trajectory controller for the hand
* @uses twist controller for the kuka arm (palm)
*
*/

namespace adaptive_grasping {

  class robotCommander {

  public:

    /** CONSTRUCTOR
    * @brief Default constructor for robotCommander
    *
    * @param hand_topic_
    *   the topic for commanding the hand closure
    * @param arm_topic_
    *   the topic for commanding the arm
    * @return null
    */
    robotCommander(std::string hand_topic_, std::string arm_topic_);

    /** DESTRUCTOR
    * @brief Default destructor for robotCommander
    *
    * @param null
    * @return null
    */
    ~robotCommander();

    /** SETREFERENCES
    * @brief Public function to set the references of palm and hand joints
    *
    * @param joints_ref_
    *   the vector containing the hand joints' speeds
    * @param palm_ref_ (must be 6d)
    *   the vector containing the reference twist for the palm
    * @return null
    */
    void setReferences(Eigen::VectorXd joints_ref_, Eigen::VectorXd palm_ref_);

    /** MOVEHANDARM
    * @brief Public function to move the hand and/or arm (if twist = 0, no arm)
    * Executes the references previously set by setReferences function
    *
    * @param null
    * @return null
    */
    void sendRefToArm();

  private:

    // The topic names for hand commanding and arm commanding
    std::string hand_topic;
    std::string arm_topic;

    // The commanded values given by contactPreserver (divided)
    Eigen::VectorXd joints_ref;
    geometry_msgs::Twist palm_ref;

    // An action client for the hand and a publisher for the arm
    std::shared_ptr<actionlib::SimpleActionClient<control_msgs::FollowJointTrajectoryAction>> move;
    ros::Publisher pub_cmd;

    /** SENDREFTOHAND
    * @brief Public function to close the hand with a given reference speed
    *
    * @param joints_ref_
    *   the vector containing the hand joints' speeds to be given
    * @return null
    */
    void sendRefToHand(Eigen::VectorXd joints_ref_);

    /** SENDREFTOARM
    * @brief Public function to move the palm of the arm, following a twist
    *
    * @param palm_ref_
    *   the twist vector containing the reference motion of the palm
    * @return null
    */
    void sendRefToArm(geometry_msgs::Twist palm_ref_);

  };

}


#endif // ROBOT_COMMANDER_H
